[package]
name = "roslibrust_codegen"
description = "Message generation of ROS messages for roslibrust"
version = "0.1.0"
authors = ["ssnover <ssnover95@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Carter12s/roslibrust"

[dependencies]
lazy_static = "1.4"
proc-macro2 = "1.0"
quote = "1.0"
roslibrust_rospack = { path = "../roslibrust_rospack" }
syn = "1.0"
