[package]
name = "roslibrust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
roslibrust = { path = "../roslibrust", default-features = false, features = ["codegen"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
diffy = "0.3.0"

[[test]]
name = "codegen_tests"