[package]
name = "roslibrust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
roslibrust = { path = "../roslibrust" }
roslibrust_codegen = { path = "../roslibrust_codegen" }
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"

[dev-dependencies]
diffy = "0.3.0"