[package]
name = "roslibrust"
version = "0.1.0"
authors = ["carter <carter@amprobotics.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.13"
# TODO look at reducing tokio features
tokio = { version = "^1.13", features = ["full"] }
tokio-tungstenite = "^0.16"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
log = "0.4.14"
simple-error = "0.2.3"
walkdir = "2.3.2"
# Using this branch for unmerged support for constants
codegen = { git = "https://github.com/gregdhill/codegen.git", branch = "associated-consts" }
#codegen = "0.1.3"

[dev-dependencies]
# Used for logging in examples
simple_logger = "1.11.0"