[workspace]

members = [
    "example_package",
    "example_package_macro",
    "roslibrust",
    "roslibrust_codegen",
    "roslibrust_codegen_macro",
    "roslibrust_genmsg",
    "roslibrust_test",
]
resolver = "2"
