[package]
name = "roslibrust"
version = "0.1.0"
authors = ["carter <carter@amprobotics.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-tungstenite = "0.14.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
bus = "2.2.3"
log = "0.4.14"
simple_logger = "1.11.0"
walkdir = "2.3.2"
codegen = "0.1.3"
