
version: "3.9"
services:
  rosbridge:
    image: carter12s/roslibrust-ci-galactic:latest
    ports:
      - "9090:9090"
    command: bash -c "source /opt/ros/galactic/setup.bash; ros2 launch rosbridge_server rosbridge_websocket_launch.xml"