[package]
name = "roslibrust_codegen_macro"
edition = "2021"
description = "Provides macro-based message generation for roslibrust"
version = "0.1.0"
repository = "https://github.com/Carter12s/roslibrust"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
roslibrust_codegen = { path = "../roslibrust_codegen" }
syn = "1.0"
