name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: carter12s/roslibrust-ci:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: /root/.cargo/bin/cargo build
    - name: Unit Tests
      run: /root/.cargo/bin/cargo test
    - name: Start rosbridge
      run: roslaunch rosbridge_server rosbridge_websocket.launch & disown & sleep 1
    - name: Integration Tests
      run: /root/.cargo/bin/cargo test --features running_bridge -- --test-threads 1
