name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  HOME: /root

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: carter12s/roslibrust-ci:v0.0.1
    steps:
    - uses: actions/checkout@v3
    - name: Debug
      run: echo $PATH; source /root/.cargo/env; echo $PATH
    - name: Build
      run: source /root/.cargo/env; cargo build
    - name: Unit Tests
      run: source /root/.cargo/env; cargo test
    - name: Start rosbridge
      run: roslaunch rosbridge_server rosbridge_websocket.launch & disown & sleep 1
    - name: Integration Tests
      run: source /root/.cargo/env; cargo test --features running_bridge -- --test-threads 1
