name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container: carter12s/roslibrust-ci:v0.0.1
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Unit Tests
      run: cargo test
    - name: Start rosbridge
      run: roslaunch rosbridge_server rosbridge_websocket.launch & disown & sleep 1
    - name: Integration Tests
      run: cargo test --features running_bridge -- --test-threads 1
